=== rostam/GTeaMinimal/src/main/java/graphtea/plugins/algorithmanimator/SampleUI.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
  GraphTea Project: https://github.com/graphtheorysoftware/GraphTea
  Copyright (C) 2008 Mathematical Science Department of Sharif University of Technology
  Distributed under the terms of the GNU General Public License (GPL): http://www.gnu.org/licenses/
  -->

<!--
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/SampleUI.dtd

--><!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE root SYSTEM "SampleUI.dtd">

    <root>
    ...
    </root>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tool EMPTY>
<!ATTLIST tool
    image CDATA #IMPLIED
    action CDATA #IMPLIED
    label CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT toolbar (tool)*>
<!ATTLIST toolbar
    place CDATA #IMPLIED
>
<!--- Put your DTDDoc comment here. -->
<!ELEMENT toolbars (toolbar)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT menu EMPTY>
<!ATTLIST menu
    action CDATA #IMPLIED
    label CDATA #IMPLIED
    accelerator CDATA #IMPLIED
    place CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT submenu (menu)*>
<!ATTLIST submenu
    label CDATA #IMPLIED
    place CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT menues (submenu)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT body EMPTY>
<!ATTLIST body
    class CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT bar EMPTY>
<!ATTLIST bar
    class CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT statusbars (bar)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sidebar EMPTY>
<!ATTLIST sidebar
    class CDATA #IMPLIED
    image CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sidebars (sidebar)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ui (toolbars|menues|body|statusbars|sidebars)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT action EMPTY>
<!ATTLIST action
    id CDATA #IMPLIED
    group CDATA #IMPLIED
    class CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT actions (action)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT root (ui|actions)*>

=== rostam/GTeaMinimal/src/main/java/graphtea/plugins/algorithmanimator/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  GraphTea Project: https://github.com/graphtheorysoftware/GraphTea
  Copyright (C) 2008 Mathematical Science Department of Sharif University of Technology
  Distributed under the terms of the GNU General Public License (GPL): http://www.gnu.org/licenses/
  -->

<!DOCTYPE root SYSTEM "/home/rostam/kara/GTeaMinimal/src/main/java/graphtea/plugins/algorithmanimator/SampleUI.dtd">
<root>
    <ui>
        <!--<toolbars>-->
        <!--<toolbar>-->
        <!--<tool label="play/pause"></tool>-->
        <!--</toolbar>-->
        <!--</toolbars>-->

        <menues>
            <submenu label="Algorithms">
                <!--<menu label="D*FS" action="do dfs"></menu>-->
                <!--<menu label="BFS" action="do bfs"></menu>-->
                <!--<menu label="Prim" action="do prim"></menu>-->
                <!--<menu label="Dijkstra" action="do dijkstra"></menu>-->
                <!--<menu label="Bellman-Ford" action="do bellmanford"></menu>-->
                <!--<menu label="Kruskal" action="do kruskal"></menu>-->
                <!--<menu label="Approximation Vertex Cover"-->
                <!--action="do app vertex cover"/>-->
                <!--<menu label="Biconnected Components"-->
                <!--action="do biconnected components"/>-->
                <!--<menu label="Topological Sort" action="do toposort"></menu>-->
                <!--<menu label="Check Acyclic" action="do acycliccheck"></menu>-->
                <!--<menu label="Sample Coloring" action="sample coloring"></menu>-->
                <!--<menu label="More..." action="more"></menu>-->

            </submenu>
            <!--<submenu label="Algorithms.Tests">-->
            <!--<menu label="Test Induced Subgraphs" action="do testinduced"></menu>-->
            <!--</submenu>            -->
        </menues>
    </ui>
    <actions>
        <action class="graphtea.plugins.algorithmanimator.DFSAnim"
                id="do dfs"/>
        <action class="graphtea.plugins.algorithmanimator.BFSAnim"
                id="do bfs"/>
        <action
                class="graphtea.plugins.algorithmanimator.BiconnectedComponentsAnim"
                id="do biconnected components"/>
        <action
                class="graphtea.plugins.algorithmanimator.TopologicalSortAnim"
                id="do toposort"/>
        <action
                class="graphtea.plugins.algorithmanimator.AcyclicCheckerAnim"
                id="do acycliccheck"/>

        <!--<action-->
        <!--class="graphtea.plugins.algorithmanimator.SampleColoringExtension"-->
        <!--id="sample coloring"/>-->
        <!---->
        <!--<action-->
        <!--class="graphtea.plugins.algorithmanimator.tests.TestInducedSubgraphs"-->
        <!--id="do testinduced"/>-->
        <!---->
        <!--<action-->
        <!--class="graphtea.plugins.algorithmanimator.More"-->
        <!--id="more"/>-->

    </actions>
</root>
